# Generated by Django 2.1.5 on 2019-02-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='season',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='series',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='viewing_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='who_watched',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
