# Generated by Django 2.1.5 on 2019-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesaver', '0002_auto_20190205_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='season',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='series',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='viewing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
