# Generated by Django 2.1.5 on 2019-02-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesaver', '0006_auto_20190206_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(),
        ),
    ]
