# Generated by Django 2.1.5 on 2019-02-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesaver', '0008_remove_movie_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='section',
            field=models.CharField(choices=[('FI', 'film'), ('SE', 'serial'), ('AN', 'anime'), ('CA', 'cartoon')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
