# Generated by Django 2.1.5 on 2019-02-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesaver', '0009_movie_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='section',
            field=models.CharField(choices=[('FI', 'Фильм'), ('SE', 'Сериал'), ('AN', 'Анимэ'), ('CA', 'Мультик')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('LO', 'Посмотреть'), ('PE', 'В ожидании'), ('IN', 'В процессе'), ('CO', 'Завершено')], max_length=2),
        ),
    ]
