# Generated by Django 2.1.5 on 2019-02-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesaver', '0010_auto_20190208_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=40, unique=True)),
                ('status_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('section_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200)),
                ('status_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Status',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='section',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
    ]
